services:
  - type: web
    name: my-blog-platform
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production