services:
  - type: web
    name: my-blog-platform
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - server.js
        - client/**